server:
  port: 8802
spring:
  application:
    name: service
  datasource:
    druid:
      stat-view-servlet:
        loginUsername: admin
        loginPassword: admin
      dynamic:
        druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
          # 连接池的配置信息
          # 初始化大小，最小，最大
          initial-size: 5
          min-idle: 5
          maxActive: 20
          # 配置获取连接等待超时的时间
          maxWait: 60000
          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          timeBetweenEvictionRunsMillis: 60000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
          minEvictableIdleTimeMillis: 300000
          # 数据库获取连接校验 Microsoft SQL Server
          validationQuery: SELECT 1
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          # 打开PSCache，并且指定每个连接上PSCache的大小
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 20
          # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
          filters: stat,slf4j
          # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
          connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      url: jdbc:mysql://localhost:3306/demoproject?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/      #服务注册中信地址
  instance:
    prefer-ip-address: true         #将IP注册到服务注册中心
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
    status-page-url: http://localhost:8802/swagger-ui.html # ${server.port}为该服务的端口号
swagger-open: true

mybatis-plus:
  mapper-locations: classpath*:com/zzp/data/**/xml/*Mapper.xml
  type-aliases-package: com.zzp.data.po
  configuration:
    map-underscore-to-camel-case: true
# 显示sql

logging:
  level:
    com:
      shrek:
        supervisor:
          dao: debug