server:
  port: 8802
spring:
  application:
    name: service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/      #服务注册中信地址
  instance:
    prefer-ip-address: true         #将IP注册到服务注册中心
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
    status-page-url: http://localhost:8801/swagger-ui.html # ${server.port}为该服务的端口号
swagger-open: true